class UpdateUsersAndRentals < ActiveRecord::Migration
  def change
    add_column :users, :first_name, :string
    add_column :users, :last_name, :string
    add_column :users, :nickname, :string
    add_column :users, :mailing_address, :string
    add_column :users, :mailing_address2, :string
    add_column :users, :mailing_city, :string
    add_column :users, :mailing_state, :string
    add_column :users, :mailing_zip, :string
    add_column :users, :birthdate, :date
    add_column :users, :phone, :string
    add_column :users, :gender, :integer
    add_column :users, :landlord_history, :integer
    add_column :users, :pets, :integer
    add_column :users, :pref_pets, :integer
    add_column :users, :smoking, :integer
    add_column :users, :pref_smoking, :integer
    add_column :users, :budget, :integer
    add_column :users, :family_size, :integer
    add_column :users, :pref_lease_term, :integer
    add_column :users, :languages, :integer
    add_column :users, :pref_share_type, :integer
    add_column :users, :pref_entrance, :integer
    add_column :users, :pref_bath, :integer
    add_column :users, :pref_kitchen, :integer
    add_column :users, :pref_furnished, :integer
    add_column :users, :pref_stairs, :integer
    add_column :users, :occupation, :string
    add_column :users, :renter_other, :text

    add_column :rentals, :deposit, :integer
    add_column :rentals, :pref_languages, :integer
    add_column :rentals, :pref_gender, :integer
    add_column :rentals, :pref_smoking, :integer
    add_column :rentals, :pref_pets, :integer
    add_column :rentals, :pref_other, :text
    add_column :rentals, :pref_lease_term, :integer
    add_column :rentals, :address, :string
    add_column :rentals, :address2, :string
    add_column :rentals, :city, :string
    add_column :rentals, :state, :string
    add_column :rentals, :zip, :string
    add_column :rentals, :share_type, :integer
    add_column :rentals, :furnished, :integer
    add_column :rentals, :entrance, :integer
    add_column :rentals, :stairs, :integer
    add_column :rentals, :bedrooms, :integer
    add_column :rentals, :bathrooms, :integer
    add_column :rentals, :kitchen, :integer
    add_column :rentals, :utilities, :integer
    add_column :rentals, :amenities, :integer
    add_column :rentals, :extras, :integer
    add_column :rentals, :safety, :integer
    add_column :rentals, :terms, :integer
    add_column :rentals, :owner_other, :text
  end
end
